import {env} from './runtime.js';
import {ApiError,endpoint,ensurePublic,headerName,cleanSecret,encrypt,decrypt,authHeaders,safeIntegration,smallJson,proxyHeaders} from './lib/security.js';
import {pollAdGuard,adguardBase} from './lib/adguard.js';
import {pollMikroTikAPI,nativeEndpoint} from './lib/mikrotik-api.js';
import {pollPangolin} from './lib/pangolin.js';
import {pollClassic,classicView} from './lib/unifi-classic.js';
export const dynamic='force-dynamic';
const response=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function handler(req:Request){try{
 const requestPath=new URL(req.url).pathname;
 if(requestPath==='/api/classic-scheduler/tick'){
  if(req.method!=='POST')throw new ApiError('POST required.',405);const expected=(env as any).CLASSIC_SCHEDULER_TOKEN;if(!expected)throw new ApiError('Unattended polling is not configured.',503);const supplied=req.headers.get('authorization')||'';const wanted='Bearer '+expected;let mismatch=supplied.length^wanted.length;for(let n=0;n<wanted.length;n++)mismatch|=(supplied.charCodeAt(n)||0)^wanted.charCodeAt(n);if(mismatch)throw new ApiError('Scheduler authentication required.',401);if(!env.DB)throw new ApiError('Database unavailable.',503);
  const records=await env.DB.prepare("SELECT integrations.* FROM integrations LEFT JOIN classic_cache ON classic_cache.id=integrations.id WHERE connector IN ('unifi-classic','pangolin','mikrotik-api','adguard') ORDER BY COALESCE(classic_cache.next_due,0),created_at LIMIT 10").all();let updated=0,failed=0,skipped=0;const results=[];for(const record of records.results){let r=await (record.connector==='adguard'?pollAdGuard:record.connector==='mikrotik-api'?pollMikroTikAPI:record.connector==='pangolin'?pollPangolin:pollClassic)(env,record);if(r.skipped)skipped++;else if(r.error)failed++;else updated++;const sites=r.data?.sites||[],organizations=r.data?.organizations||[];results.push({id:record.id,name:record.name,status:r.skipped?record.status:r.status,error:r.error,stale:r.stale,lastSuccess:r.lastSuccess,sites:sites.length+organizations.reduce((n:number,o:any)=>n+o.sites.length,0),resources:organizations.reduce((n:number,o:any)=>n+o.resources.length+o.privateResources.length,0),devices:sites.reduce((n:number,s:any)=>n+s.devices.length,0),connectedClients:sites.reduce((n:number,s:any)=>n+s.connectedClientCount,0)})}return response({updated,failed,skipped,results});
 }
 const owner=req.headers.get('oai-authenticated-user-id');if(!owner)throw new ApiError('Sign in to access Mission Control.',401);
 if(!env.DB)throw new ApiError('Database unavailable.',503);const db=env.DB;
 if(!['GET','HEAD'].includes(req.method)){if(req.headers.get('origin')!==((env as any).SITE_ORIGIN||new URL(req.url).origin)||req.headers.get('sec-fetch-site')==='cross-site')throw new ApiError('Request origin rejected.',403);if(!req.headers.get('content-type')?.startsWith('application/json'))throw new ApiError('JSON required.',415)}
 const path=new URL(req.url).pathname.replace(/^\/api\//,'').split('/');
 let body:any={};if(!['GET','HEAD'].includes(req.method)&&req.body){const text=await req.text();if(text.length>180000)throw new ApiError('Request too large.',413);if(text.trim()){try{body=JSON.parse(text)}catch{throw new ApiError('Invalid JSON.')}}}
 async function audit(action:string,name:string){await db.prepare('INSERT INTO audit (id,owner,action,name,time) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),owner,action,name,new Date().toISOString()).run()}
 if(path[0]==='workspace'){
  if(req.method==='GET'){let r:any=await db.prepare('SELECT data FROM workspaces WHERE owner=?').bind(owner).first();return response({data:r?JSON.parse(r.data):null})}
  if(req.method==='PUT'){let data:any={};for(let k of ['customers','assets','alerts','tasks','activity']){if(!Array.isArray(body[k])||body[k].length>500)throw new ApiError('Invalid workspace records.');data[k]=body[k]};await db.prepare('INSERT INTO workspaces (owner,data,updated_at) VALUES (?,?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at').bind(owner,JSON.stringify(data),new Date().toISOString()).run();return response({saved:true})}
 }
 if(path[0]==='assets'){
  if(req.method!=='DELETE')throw new ApiError('Method not allowed.',405);if(path[1]===undefined||body.integrationId||body.assetId)throw new ApiError('Integration-managed assets can only be removed by deleting their integration.',403);const workspace:any=await db.prepare('SELECT data FROM workspaces WHERE owner=?').bind(owner).first();if(!workspace)throw new ApiError('Workspace not found.',404);const data=JSON.parse(workspace.data);let name='Asset';
  if(path[1]!==undefined){const index=Number(path[1]);if(!/^\d{1,3}$/.test(path[1])||!data.assets[index])throw new ApiError('Asset not found.',404);const asset=data.assets[index];if(JSON.stringify(body.expected)!==JSON.stringify(asset))throw new ApiError('This asset changed. Close this dialog and try again.',409);name=asset.name;data.assets.splice(index,1);const changed=await db.prepare('UPDATE workspaces SET data=?,updated_at=? WHERE owner=? AND data=?').bind(JSON.stringify(data),new Date().toISOString(),owner,workspace.data).run();if(!changed.meta.changes)throw new ApiError('Workspace changed during deletion. Try again.',409)}
  await audit('Deleted asset from Mission Control',name);const records=await db.prepare('SELECT * FROM integrations WHERE owner=? ORDER BY created_at').bind(owner).all();return response({data,integrations:records.results.map(safeIntegration)});
 }
 if(path[0]==='customers'){
  const workspace:any=await db.prepare('SELECT data FROM workspaces WHERE owner=?').bind(owner).first();if(!workspace)throw new ApiError('Workspace not found.',404);const data=JSON.parse(workspace.data);if(req.method==='GET')return response({customers:data.customers});
  const creating=req.method==='POST'&&!path[1];if(!creating&&!['PATCH','DELETE'].includes(req.method))throw new ApiError('Method not allowed.',405);const index=Number(path[1]);let previous:any=null;
  if(!creating){if(!/^\d{1,3}$/.test(path[1]||'')||!data.customers[index])throw new ApiError('Customer not found.',404);previous=data.customers[index];if(body.expectedName!==previous.name)throw new ApiError('This customer changed. Close this dialog and try again.',409);if(data.customers.filter((c:any)=>c.name===previous.name).length!==1)throw new ApiError('Duplicate customer names must be resolved before changing linked records.',409)}
  let replacement:any=null;if(req.method!=='DELETE'){const name=String(body.name||'').trim(),type=String(body.type||'').trim(),contact=String(body.contact||'').trim();if(!name||name.length>200||type.length>200||contact.length>200)throw new ApiError('Customer name is required; fields must be at most 200 characters.');if(data.customers.some((c:any,n:number)=>(creating||n!==index)&&c.name.trim().toLowerCase()===name.toLowerCase()))throw new ApiError('A customer with that name already exists.',409);replacement={...previous,name,type,contact,status:previous?.status||'Healthy'};if(creating){if(data.customers.length>=500)throw new ApiError('Maximum 500 customers.');data.customers.push(replacement)}else data.customers[index]=replacement}else data.customers.splice(index,1);
  const deleting=req.method==='DELETE',customer=replacement?.name||'';if(deleting)data.assets=data.assets.filter((asset:any)=>asset.customer!==previous.name);else if(previous&&previous.name!==customer)for(const asset of data.assets)if(asset.customer===previous.name)asset.customer=customer;
  const encoded=JSON.stringify(data),now=new Date().toISOString(),statements=[db.prepare('UPDATE workspaces SET data=?,updated_at=? WHERE owner=? AND data=?').bind(encoded,now,owner,workspace.data)];if(deleting){const guard='EXISTS(SELECT 1 FROM workspaces WHERE owner=? AND data=? AND updated_at=?)';statements.push(db.prepare('DELETE FROM classic_cache WHERE owner=? AND id IN(SELECT id FROM integrations WHERE owner=? AND customer=?) AND '+guard).bind(owner,owner,previous.name,owner,encoded,now),db.prepare('DELETE FROM integrations WHERE owner=? AND customer=? AND '+guard).bind(owner,previous.name,owner,encoded,now))}else if(previous&&previous.name!==customer)statements.push(db.prepare('UPDATE integrations SET customer=? WHERE owner=? AND customer=? AND EXISTS(SELECT 1 FROM workspaces WHERE owner=? AND data=? AND updated_at=?)').bind(customer,owner,previous.name,owner,encoded,now));const changed=await db.batch(statements);if(!changed[0].meta.changes)throw new ApiError('Workspace changed during the save. Try again.',409);await audit(creating?'Added customer':req.method==='DELETE'?'Deleted customer':'Updated customer',replacement?.name||previous.name);const records=await db.prepare('SELECT * FROM integrations WHERE owner=? ORDER BY created_at').bind(owner).all();return response({data,integrations:records.results.map(safeIntegration)});
 }
 if(path[0]==='audit'&&req.method==='GET'){const r=await db.prepare('SELECT action,name,time FROM audit WHERE owner=? ORDER BY time DESC LIMIT 20').bind(owner).all();return response({events:r.results})}
 if(path[0]!=='integrations')throw new ApiError('Not found.',404);
 const id=path[1];let current:any=null;if(id){current=await db.prepare('SELECT * FROM integrations WHERE id=? AND owner=?').bind(id,owner).first();if(!current)throw new ApiError('Integration not found.',404)}
 if(req.method==='GET'&&!id){let r=await db.prepare('SELECT * FROM integrations WHERE owner=? ORDER BY created_at').bind(owner).all();return response({integrations:r.results.map(safeIntegration)})}
 if(current?.connector==='mikrotik'&&req.method==='POST'&&['poll','test'].includes(path[2]))return response({status:'Connector removed',error:'MikroTik REST has been removed. Edit this integration and select MikroTik Native API.',stale:true,lastSuccess:null,data:null});
 if(current?.status==='Credentials required'&&req.method==='POST'&&['test','poll'].includes(path[2]))return response({status:'Credentials required',error:'Edit this integration and enter its credentials locally.',stale:true,lastSuccess:null,data:null});
 if(['unifi-classic','pangolin','mikrotik-api','adguard'].includes(current?.connector)&&req.method==='GET'&&path[2]==='data'){const row=await db.prepare('SELECT * FROM classic_cache WHERE id=? AND owner=?').bind(id,owner).first();return response(classicView(row))}
 if(['unifi-classic','pangolin','mikrotik-api','adguard'].includes(current?.connector)&&req.method==='POST'&&['poll','test'].includes(path[2])){let result=await (current.connector==='adguard'?pollAdGuard:current.connector==='mikrotik-api'?pollMikroTikAPI:current.connector==='pangolin'?pollPangolin:pollClassic)(env,current,{force:path[2]==='test',test:path[2]==='test'});if(path[2]==='test')await audit((current.connector==='adguard'?'AdGuard Home':['mikrotik','mikrotik-api'].includes(current.connector)?'MikroTik':current.connector==='pangolin'?'Pangolin':'Classic')+' connection test: '+result.status,current.name);return response(result)}
 if(req.method==='DELETE'&&id){await db.batch([db.prepare('DELETE FROM classic_cache WHERE id=? AND owner=?').bind(id,owner),db.prepare('DELETE FROM integrations WHERE id=? AND owner=?').bind(id,owner)]);await audit('Deleted integration',current.name);return response({deleted:true})}
 if((req.method==='POST'&&!id)||(req.method==='PATCH'&&id)){
 const connector=body.connector||current?.connector||'generic';if(!['generic','unifi-classic','pangolin','mikrotik-api','adguard'].includes(connector))throw new ApiError('Unknown connector.');if(connector==='unifi-classic'&&(body.mode!=='direct'||body.auth!=='basic'))throw new ApiError('Classic Network uses a direct HTTPS base URL and a local account.');if(connector==='pangolin'&&(body.mode!=='direct'||body.auth!=='bearer'))throw new ApiError('Pangolin uses a direct HTTPS Integration API URL and a bearer API key.');if(connector==='adguard'&&(body.mode!=='direct'||body.auth!=='basic'))throw new ApiError('AdGuard Home uses a direct HTTP(S) web URL and Basic username/password authentication.');const orgId=String(body.orgId??current?.org_id??'').trim();if(['.','..'].includes(orgId)||orgId.length>256||/[\r\n\0]/.test(orgId))throw new ApiError('Invalid organization ID.');const name=String(body.name||'').trim();if(!name||name.length>100)throw new ApiError('Enter an integration name (maximum 100 characters).');if(!['direct','bridge'].includes(body.mode)||!['none','bearer','header','basic'].includes(body.auth))throw new ApiError('Invalid connection or authentication method.');const url=connector==='adguard'?adguardBase(String(body.endpoint||'')):connector==='mikrotik-api'?nativeEndpoint(String(body.endpoint||'')):endpoint(String(body.endpoint||''));if(connector==='mikrotik-api'&&(body.mode!=='direct'||body.auth!=='basic'||body.proxyAuth===true))throw new ApiError('Native MikroTik API uses a direct TCP/TLS endpoint and a local username/password, without HTTP proxy authentication.');if(connector==='unifi-classic'&&new URL(url).pathname!=='/')throw new ApiError('Use the Classic controller base URL without an API path.');if(connector==='pangolin'&&!['/','/v1','/v1/'].includes(new URL(url).pathname))throw new ApiError('Use the Pangolin Integration API host, optionally ending in /v1.');const target=body.mode==='bridge'?endpoint(String(body.target||''),true):null;const header=body.auth==='header'?headerName(String(body.header||'')):null;
 let previous:any=current?await decrypt(current.encrypted,(env as any).INTEGRATION_ENCRYPTION_KEY,owner+':'+current.id):{};
 const proxyAuth=connector==='mikrotik-api'?false:body.proxyAuth===undefined?!!current?.proxy_auth:body.proxyAuth===true;if(proxyAuth&&body.auth==='header'&&/^p-access-token(-id)?$/i.test(header||''))throw new ApiError('Use a different service API header from the Pangolin token headers.');const supplied=body.credential||{};const secret:any={};for(const k of ['key','username','password','bridgeToken','proxyId','proxyToken'])secret[k]=cleanSecret(supplied[k]||previous[k]||'');
 if(proxyAuth&&(!secret.proxyId||!secret.proxyToken))throw new ApiError('Pangolin token ID and access token are both required.');if(!proxyAuth){secret.proxyId='';secret.proxyToken=''}
 if(body.auth==='basic'&&(!secret.username||!secret.password))throw new ApiError('Username and password required.');if(['bearer','header'].includes(body.auth)&&!secret.key)throw new ApiError('API key or token required.');if(body.mode==='bridge'&&secret.bridgeToken.length<32)throw new ApiError('Bridge token must have at least 32 characters.');
 if(body.auth==='none'){secret.key='';secret.username='';secret.password=''}else if(body.auth==='basic')secret.key='';else{secret.username='';secret.password=''}if(body.mode!=='bridge')secret.bridgeToken='';
 const recordId=id||crypto.randomUUID();const encrypted=await encrypt(secret,(env as any).INTEGRATION_ENCRYPTION_KEY,owner+':'+recordId);const customer=String(body.customer||'').trim().slice(0,200);const now=new Date().toISOString();
 const connectionChanged=!current||connector!==current.connector||orgId!==(current.org_id||'')||url!==current.endpoint||target!==current.target||body.mode!==current.mode||body.auth!==current.auth||header!==current.header||proxyAuth!==!!current.proxy_auth||JSON.stringify(secret)!==JSON.stringify(previous);
 if(id&&!connectionChanged)await db.prepare('UPDATE integrations SET name=?,customer=? WHERE id=? AND owner=?').bind(name,customer,id,owner).run();
 else if(id)await db.prepare('UPDATE integrations SET connector=?,org_id=?,revision=revision+1,name=?,endpoint=?,target=?,mode=?,auth=?,header=?,customer=?,encrypted=?,proxy_auth=?,status=?,http_code=NULL,latency=NULL,checked_at=NULL WHERE id=? AND owner=?').bind(connector,orgId,name,url,target,body.mode,body.auth,header,customer,encrypted,proxyAuth?1:0,'Not tested',id,owner).run();else{let count:any=await db.prepare('SELECT COUNT(*) AS n FROM integrations WHERE owner=?').bind(owner).first();if(count.n>=100)throw new ApiError('Maximum 100 integrations.',400);await db.prepare('INSERT INTO integrations (id,owner,connector,org_id,name,endpoint,target,mode,auth,header,customer,encrypted,proxy_auth,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(recordId,owner,connector,orgId,name,url,target,body.mode,body.auth,header,customer,encrypted,proxyAuth?1:0,'Not tested',now).run()}
 if(id&&connectionChanged)await db.prepare('DELETE FROM classic_cache WHERE id=? AND owner=?').bind(id,owner).run();
 await audit(id?'Updated integration':'Added integration',name);return response({saved:true,id:recordId})
 }
 if(req.method==='POST'&&id&&['test','poll'].includes(path[2])){
 const polling=path[2]==='poll';
 // Claim a test window atomically, limiting repeated requests for each integration.
 const claimed=await db.prepare("UPDATE integrations SET checked_at=? WHERE id=? AND owner=? AND (checked_at IS NULL OR checked_at<?)").bind(new Date().toISOString(),id,owner,new Date(Date.now()-(polling?60000:10000)).toISOString()).run();if(!claimed.meta.changes){if(polling)return response({...safeIntegration(current),skipped:true});throw new ApiError('Wait 10 seconds between connection tests.',429);}
 const start=Date.now();let status='Connection failed',httpCode:null|number=null;
 try{await ensurePublic(current.endpoint);const secret=await decrypt(current.encrypted,(env as any).INTEGRATION_ENCRYPTION_KEY,owner+':'+id);const headers=authHeaders(current.auth,current.header,secret);
 if(current.mode==='bridge'){const r=await fetch(current.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+secret.bridgeToken,...proxyHeaders(secret,!!current.proxy_auth)},body:JSON.stringify({url:current.target,headers}),redirect:'manual',signal:AbortSignal.timeout(12000)});if(r.status>=300&&r.status<400){await r.body?.cancel();status='Bridge redirect blocked'}else if(!r.ok){await r.body?.cancel();status='Bridge HTTP '+r.status}else{const result=await smallJson(r);httpCode=Number.isInteger(result.status)&&result.status>=100&&result.status<=599?result.status:null;if(!httpCode)status='Invalid bridge response';else status=httpCode>=300&&httpCode<400?'Redirect blocked':httpCode>=200&&httpCode<300?'Connected':'HTTP '+httpCode}}
 else{const r=await fetch(current.endpoint,{method:'GET',headers:{...headers,...proxyHeaders(secret,!!current.proxy_auth)},redirect:'manual',signal:AbortSignal.timeout(10000)});httpCode=r.status;await r.body?.cancel();status=r.status>=300&&r.status<400?'Redirect blocked':r.ok?'Connected':'HTTP '+r.status}
 }catch(e){status=e instanceof ApiError?'Endpoint rejected or DNS unavailable':'Connection failed · check endpoint, TLS and reachability'}
 const latency=Date.now()-start,checkedAt=new Date().toISOString();await db.prepare('UPDATE integrations SET status=?,http_code=?,latency=?,checked_at=? WHERE id=? AND owner=?').bind(status,httpCode,latency,checkedAt,id,owner).run();if(!polling)await audit('Connection test: '+status,current.name);return response({status,httpCode,latency,checkedAt})
 }
 throw new ApiError('Method not allowed.',405);
 }catch(e){return response({error:e instanceof ApiError?e.message:'Server request failed.'},e instanceof ApiError?e.status:500)}}
export const GET=handler;export const POST=handler;export const PATCH=handler;export const PUT=handler;export const DELETE=handler;
