import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {randomUUID} from 'node:crypto';
import {nativeEndpoint} from './lib/mikrotik-api.js';
import {LocalDB} from './db.mjs';import {env} from './runtime.js';import {verifyPassword,authenticated,createSession,revokeSession,cookie} from './auth.mjs';import * as routes from './api.js';import {encrypt} from './lib/security.js';
export function startServer(config,{database='./data/mission.sqlite',port=8080,host='0.0.0.0',poll=true}={}){
 if(!/^[a-f0-9]{64}$/.test(config.encryptionKey))throw Error('Invalid encryption key.');const db=new LocalDB(database);Object.assign(env,{DB:db,INTEGRATION_ENCRYPTION_KEY:config.encryptionKey,SITE_ORIGIN:config.origin});const owner=config.owner||'local-admin';
 db.sql.prepare('INSERT OR IGNORE INTO workspaces VALUES (?,?,?)').run(owner,JSON.stringify({customers:[],assets:[],alerts:[],tasks:[],activity:[]}),new Date().toISOString());
 const failures=new Map(),publicDir=fileURLToPath(new URL('./public/',import.meta.url));let polling=false;
 const loginPage='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Sign in · JDLN Mission Control</title><link rel="stylesheet" href="/style.css"></head><body style="display:grid;place-items:center;min-height:100vh"><main style="width:min(420px,90vw);padding:30px"><h1>JDLN Mission Control</h1><p>Your private operations workspace</p><form id="login"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="btn primary">Sign in</button><p id="error" role="alert"></p></form><script src="/login.js"></script></main></body></html>';
 function send(res,status,body,type='application/json',headers={}){res.writeHead(status,{'Content-Type':/^(text\/|application\/json$|image\/svg\+xml$)/.test(type)?type+'; charset=utf-8':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','X-Frame-Options':'DENY',...headers});res.end(type==='application/json'?JSON.stringify(body):body)}
 async function body(req,limit=180000){let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>limit)throw Error('Request too large.')}return text}
 function originOK(req){return req.headers.origin===config.origin&&req.headers['sec-fetch-site']!=='cross-site'}
 const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local'),pathname=url.pathname;
 if(pathname==='/healthz'&&req.method==='GET')return send(res,200,{status:'ok',version:process.env.MISSION_VERSION||'development'});
 if(pathname==='/login'&&req.method==='GET')return send(res,200,loginPage,'text/html');
 if(pathname==='/login.js'&&req.method==='GET')return send(res,200,"document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const r=await fetch('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});if(r.ok)location.href='/dashboard.html';else document.querySelector('#error').textContent=(await r.json()).error;};",'text/javascript');
 if(pathname==='/auth/login'&&req.method==='POST'){if(!originOK(req)||!req.headers['content-type']?.startsWith('application/json'))return send(res,403,{error:'Request rejected.'});const ip=req.socket.remoteAddress,now=Date.now();if(failures.size>10000)failures.clear();let state=failures.get(ip)||{count:0,time:now};if(now-state.time>60000)state={count:0,time:now};if(state.count>=5)return send(res,429,{error:'Wait a minute before trying again.'});state.count++;failures.set(ip,state);let b;try{b=JSON.parse(await body(req,16384))}catch{return send(res,400,{error:'Invalid request.'})}if(typeof b.password!=='string'||b.password.length>1024||!verifyPassword(b.password,config.password)||b.username!==config.username)return send(res,401,{error:'Invalid username or password.'});failures.delete(ip);return send(res,200,{signedIn:true},'application/json',{'Set-Cookie':cookie(createSession(db),config.origin)})}
 if(!authenticated(db,req.headers.cookie)){if(pathname.startsWith('/api/')||pathname.startsWith('/auth/'))return send(res,401,{error:'Sign in required.'});if(pathname!=='/style.css'&&pathname!=='/favicon.svg')return send(res,302,'','text/plain',{Location:'/login'})}
 if(pathname==='/auth/logout'&&req.method==='POST'){if(!originOK(req))return send(res,403,{error:'Request rejected.'});revokeSession(db,req.headers.cookie);return send(res,200,{signedOut:true},'application/json',{'Set-Cookie':cookie('',config.origin)})}
 if(pathname.startsWith('/api/')){if(!['GET','POST','PATCH','PUT','DELETE'].includes(req.method))return send(res,405,{error:'Method not allowed.'});if(!['GET','HEAD'].includes(req.method)&&(!originOK(req)||!req.headers['content-type']?.startsWith('application/json')))return send(res,403,{error:'Request rejected.'});if(pathname==='/api/classic-scheduler/tick')return send(res,404,{error:'Not found.'});
 const raw=['GET','HEAD'].includes(req.method)?undefined:await body(req,pathname==='/api/migration/import'?1024*1024:180000);
 if(pathname==='/api/migration/import'&&req.method==='POST'){const report=JSON.parse(raw),fields={customers:['name','type','contact','status'],assets:['name','type','customer','address','status','cpu','ram'],alerts:['id','title','source','severity','detail','ack'],tasks:['title','agent','status'],activity:['text','time']},workspace={};for(const [key,keys] of Object.entries(fields)){if(!Array.isArray(report[key])||report[key].length>500)return send(res,400,{error:'Invalid migration records.'});workspace[key]=report[key].map(record=>Object.fromEntries(keys.filter(k=>['string','number','boolean'].includes(typeof record[k])).map(k=>[k,record[k]])))}const current=await db.prepare('SELECT data FROM workspaces WHERE owner=?').bind(owner).first();if(Object.values(JSON.parse(current.data)).some(v=>Array.isArray(v)&&v.length))return send(res,409,{error:'Import requires an empty workspace.'});if(!Array.isArray(report.integrations)||report.integrations.length>100)return send(res,400,{error:'Invalid integration settings.'});
 const statements=[db.prepare('UPDATE workspaces SET data=?,updated_at=? WHERE owner=? AND data=?').bind(JSON.stringify(workspace),new Date().toISOString(),owner,current.data)];for(const i of report.integrations){if(typeof i.name!=='string'||i.name.length>100||typeof i.endpoint!=='string'||i.endpoint.length>2048)throw Error('Invalid integration settings.');const u=new URL(i.endpoint);if(i.connector==='mikrotik-api')nativeEndpoint(i.endpoint);if(u.username||u.password||u.hash||u.search||!(i.connector==='mikrotik-api'?['tcp:','tls:']:['http:','https:']).includes(u.protocol))throw Error('Invalid endpoint.');const id=randomUUID(),connector=['unifi-classic','pangolin','mikrotik','mikrotik-api','adguard'].includes(i.connector)?i.connector:'generic',auth=['none','bearer','header','basic'].includes(i.auth)?i.auth:'bearer';statements.push(db.prepare('INSERT INTO integrations (id,owner,connector,org_id,name,endpoint,mode,auth,header,customer,encrypted,status,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM workspaces WHERE owner=? AND data=?)').bind(id,owner,connector,String(i.orgId||'').slice(0,256),i.name,u.href,'direct',auth,typeof i.header==='string'?i.header.slice(0,64):null,String(i.customer||'').slice(0,200),await encrypt({},config.encryptionKey,owner+':'+id),'Credentials required',new Date().toISOString(),owner,JSON.stringify(workspace)))}const result=await db.batch(statements);if(!result[0].meta.changes)return send(res,409,{error:'Workspace changed. Try again.'});return send(res,200,{imported:true,credentialsImported:false})}
 // Identity is generated after local session validation; incoming identity headers are discarded.
 const headers=new Headers();for(const name of ['origin','content-type','sec-fetch-site'])if(req.headers[name])headers.set(name,req.headers[name]);headers.set('oai-authenticated-user-id',owner);const response=await routes[req.method](new Request(config.origin+pathname,{method:req.method,headers,...(raw===undefined?{}:{body:raw})}));res.writeHead(response.status,Object.fromEntries(response.headers));return res.end(Buffer.from(await response.arrayBuffer()))}
 if(req.method!=='GET')return send(res,405,{error:'Method not allowed.'});const file=pathname==='/'?'dashboard.html':pathname.slice(1);if(!/^[a-zA-Z0-9_.-]+$/.test(file))return send(res,404,{error:'Not found.'});const asset=path.join(publicDir,file);if(!fs.existsSync(asset)||!fs.statSync(asset).isFile())return send(res,404,{error:'Not found.'});const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.zip':'application/zip'};return send(res,200,fs.readFileSync(asset),mime[path.extname(file)]||'application/octet-stream');
 }catch{return send(res,400,{error:'Request failed. Check the input and server configuration.'})}});
 async function pollAll(){if(polling)return;polling=true;try{const records=(await db.prepare("SELECT id FROM integrations WHERE status!='Credentials required' AND connector!='mikrotik' ORDER BY created_at").all()).results;await Promise.allSettled(records.map(r=>routes.POST(new Request(config.origin+'/api/integrations/'+r.id+'/poll',{method:'POST',headers:{'oai-authenticated-user-id':owner,Origin:config.origin,'Content-Type':'application/json'},body:'{}'}))))}finally{polling=false}}
 const timer=poll?setInterval(()=>pollAll().catch(()=>{}),60000):null;timer?.unref();server.listen(port,host,()=>{if(poll)pollAll().catch(()=>{});console.log('Mission Control listening; credentials are never logged.');});return {server,db,pollAll,async close(){if(timer)clearInterval(timer);await new Promise(resolve=>server.close(resolve));db.close()}};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const config=JSON.parse(fs.readFileSync(process.env.CONFIG_FILE||'/config/config.json','utf8'));const app=startServer(config,{database:process.env.DATABASE_FILE||'/data/mission.sqlite',port:Number(process.env.PORT||8080)});process.on('SIGTERM',()=>app.close().then(()=>process.exit(0)))}
