import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {passwordHash} from '../auth.mjs';import {startServer} from '../server.mjs';import {endpoint} from '../lib/security.js';
test('Local login, session spoof resistance, CSRF, CRUD, encrypted credentials, migration and persistent SQLite',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mission-test-'));const config={origin:'http://localhost:8080',username:'admin',password:passwordHash('test-password-123'),encryptionKey:'ab'.repeat(32),allowedTargets:'192.168.5.3:3003,unifi.internal:8443',owner:'local-admin'};const app=startServer(config,{database:path.join(dir,'db.sqlite'),port:0,host:'127.0.0.1',poll:false});await new Promise(r=>app.server.once('listening',r));const base='http://127.0.0.1:'+app.server.address().port;let session='';
 async function request(url,method='GET',data,headers={}){const r=await fetch(base+url,{method,redirect:'manual',headers:{Origin:config.origin,'Content-Type':'application/json',Cookie:session,...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});return {r,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.text()}}
 try{assert.equal((await request('/api/integrations','GET',undefined,{'oai-authenticated-user-id':'local-admin'})).r.status,401);assert.equal((await request('/dashboard.html')).r.status,302);assert.equal((await request('/auth/login','POST',{username:'admin',password:'wrong'})).r.status,401);let login=await request('/auth/login','POST',{username:'admin',password:'test-password-123'});assert.equal(login.r.status,200);session=login.r.headers.get('set-cookie').split(';')[0];assert(login.r.headers.get('set-cookie').includes('HttpOnly'));assert.equal((await request('/api/workspace')).r.status,200);assert.equal((await request('/api/customers','POST',{name:'School'}, {Origin:'http://evil.test'})).r.status,403);
 const report={customers:[{name:'School',type:'Education',contact:'IT',status:'Healthy',password:'NO-IMPORT'}],assets:[{name:'Manual',customer:'School'}],alerts:[],tasks:[],activity:[],integrations:[{name:'Pangolin',connector:'pangolin',endpoint:'http://192.168.5.3:3003',auth:'bearer',customer:'School',credential:{key:'NO-IMPORT'}}]};assert.equal((await request('/api/migration/import','POST',report)).r.status,200);assert(!JSON.stringify((await request('/api/workspace')).data).includes('NO-IMPORT'));const integrations=(await request('/api/integrations')).data.integrations;assert.equal(integrations[0].status,'Credentials required');assert.equal((await request('/api/migration/import','POST',report)).r.status,409);
 const id=integrations[0].id,updated=await request('/api/integrations/'+id,'PATCH',{name:'Pangolin',connector:'pangolin',endpoint:report.integrations[0].endpoint,auth:'bearer',mode:'direct',customer:'School',credential:{key:'VERY-SECRET'}});assert.equal(updated.r.status,200,JSON.stringify(updated.data));const stored=await app.db.prepare('SELECT encrypted FROM integrations WHERE id=?').bind(id).first();assert(!stored.encrypted.includes('VERY-SECRET'));assert(!JSON.stringify((await request('/api/integrations')).data).includes('VERY-SECRET'));assert.equal((await request('/api/assets','DELETE',{integrationId:id,assetId:'live'})).r.status,403);assert.equal((await request('/api/customers/0','DELETE',{expectedName:'School'})).r.status,200);assert.equal((await request('/api/integrations')).data.integrations.length,0);
 assert.equal(endpoint('http://192.168.5.3:3003/v1'),'http://192.168.5.3:3003/v1');assert.throws(()=>endpoint('http://192.168.5.4:3003/v1'),/not allowed/);assert.throws(()=>endpoint('http://169.254.169.254/'));assert.equal((await request('/auth/logout','POST',{})).r.status,200);assert.equal((await request('/api/workspace')).r.status,401);
 }finally{await app.close();fs.rmSync(dir,{recursive:true,force:true})}
});
