import {ApiError,ensurePublic,endpoint,decrypt,proxyHeaders,smallJson} from './security.js';
import {classicView} from './unifi-classic.js';
export class PangolinError extends Error{}
const text=v=>typeof v==='string'?v.slice(0,256):null;
const id=v=>typeof v==='string'||typeof v==='number'?String(v).slice(0,256):null;
export class PangolinSession{
 constructor(base,secret,options={}){const u=new URL(endpoint(base));if(!['/','/v1','/v1/'].includes(u.pathname))throw new PangolinError('Use the Pangolin Integration API host, optionally ending in /v1.');this.base=u.origin+'/v1';this.secret=secret;this.fetch=options.fetcher||fetch;this.signal=options.signal;this.proxy=options.proxy;this.orgId=options.orgId}
 async read(path){if(!/^\/orgs\?limit=100&offset=\d+$/.test(path)&&!/^\/org\/[^/?#]+\/(sites|resources|site-resources)\?pageSize=100&page=\d+$/.test(path))throw new PangolinError('Read endpoint not allowed.');let r;try{r=await this.fetch(this.base+path,{method:'GET',headers:{Accept:'application/json',Authorization:'Bearer '+this.secret.key,...proxyHeaders(this.secret,this.proxy)},redirect:'manual',signal:this.signal?AbortSignal.any([this.signal,AbortSignal.timeout(10000)]):AbortSignal.timeout(10000)})}catch{throw new PangolinError('Pangolin connection or TLS request failed.')}if(r.status!==200){await r.body?.cancel();const e=new PangolinError(r.status>=300&&r.status<400?'Pangolin API redirected to a login or proxy page.':r.status===401||r.status===403?'Pangolin API denied access. Check the API key and its read permissions.':r.status===404?'Pangolin Integration API route not found. Enable the Integration API and route this HTTPS host to its service (normally port 3003).':'Pangolin API returned HTTP '+r.status+'.');e.httpStatus=r.status;throw e}let value;try{value=await smallJson(r,4*1024*1024)}catch{throw new PangolinError('Pangolin returned HTML or invalid JSON. Use the Integration API host, rather than the dashboard host.')}if(value?.success!==true||value.error===true||!value.data)throw new PangolinError('Pangolin API reported an integration error.');return value.data}
 async list(path,key,orgs=false){let out=[];for(let page=1;page<=10;page++){const data=await this.read(path+(orgs?'?limit=100&offset='+((page-1)*100):'?pageSize=100&page='+page));if(!Array.isArray(data[key]))throw new PangolinError('Pangolin returned an invalid '+key+' list.');out.push(...data[key]);const total=data.pagination?.total;if(Number.isFinite(total)&&out.length>=total)return out;if(data[key].length<100)return out;if(out.length>=1000)throw new PangolinError('Pangolin record limit exceeded. Split this integration by organization.')}throw new PangolinError('Pangolin pagination limit exceeded.')}
 async collect(){let orgs;if(this.orgId)orgs=[{orgId:this.orgId,name:this.orgId}];else{try{orgs=await this.list('/orgs','orgs',true)}catch(e){if(e.httpStatus===403)throw new PangolinError('Enter your Organization ID in Edit integration. Organization keys cannot discover organizations; keep using your existing organization API key.');throw e}}if(!orgs.length)throw new PangolinError('No accessible Pangolin organizations returned.');if(orgs.length>20)throw new PangolinError('More than 20 organizations; configure an Organization ID.');const organizations=[],warnings=[];for(const org of orgs){const orgId=id(org.orgId);if(!orgId||['.','..'].includes(orgId))throw new PangolinError('Pangolin organization identifier is missing.');const path='/org/'+encodeURIComponent(orgId);const sites=await this.list(path+'/sites','sites');const resources=await this.list(path+'/resources','resources');let privateResources=[];try{privateResources=await this.list(path+'/site-resources','siteResources')}catch(e){if(![403,404].includes(e.httpStatus))throw e;warnings.push('Private resources unavailable for '+orgId+'. Allow List Site Resources to include them.')}organizations.push({orgId,name:text(org.name)||orgId,sites:sites.map(s=>({siteId:id(s.siteId),name:text(s.name),type:text(s.type),online:s.type==='local'?null:typeof s.online==='boolean'?s.online:null,version:text(s.newtVersion),resourceCount:typeof s.resourceCount==='number'?s.resourceCount:null})),resources:resources.map(r=>({resourceId:id(r.resourceId),name:text(r.name),kind:'public',enabled:typeof r.enabled==='boolean'?r.enabled:null,domain:text(r.fullDomain),health:text(r.health)})),privateResources:privateResources.map(r=>({resourceId:id(r.siteResourceId),name:text(r.name),kind:'private',enabled:typeof r.enabled==='boolean'?r.enabled:null}))})}return {organizations,warnings}}
}
export async function pollPangolin(env,record,{force=false,test=false,fetcher=fetch,now=Date.now()}={}){
 const db=env.DB,owner=record.owner,id=record.id,revision=record.revision;await db.prepare("INSERT INTO classic_cache (id,owner,revision) SELECT id,owner,revision FROM integrations WHERE id=? AND owner=? AND revision=? AND connector='pangolin' ON CONFLICT(id) DO NOTHING").bind(id,owner,revision).run();const lease=crypto.randomUUID();const claimed=await db.prepare('UPDATE classic_cache SET lease=?,lease_until=?,last_attempt=? WHERE id=? AND owner=? AND revision=? AND lease_until<=? AND (next_due<=? OR ?=1)').bind(lease,now+90000,new Date(now).toISOString(),id,owner,revision,now,now,force?1:0).run();if(!claimed.meta.changes){let row=await db.prepare('SELECT * FROM classic_cache WHERE id=? AND owner=?').bind(id,owner).first();return {...classicView(row),skipped:true,status:row?.lease_until>now?'Poll already in progress':'Cached · next poll not due'}}
 let snapshot,error=null;const start=Date.now();try{await ensurePublic(record.endpoint,fetcher);let secret=await decrypt(record.encrypted,env.INTEGRATION_ENCRYPTION_KEY,owner+':'+id);const session=new PangolinSession(record.endpoint,secret,{fetcher,signal:AbortSignal.timeout(50000),proxy:!!record.proxy_auth,orgId:record.org_id});snapshot=await session.collect();if(JSON.stringify(snapshot).length>750000)throw new PangolinError('Whitelisted snapshot exceeds the storage limit.')}catch(e){error=e instanceof PangolinError?e.message:e instanceof ApiError?'Endpoint DNS validation failed.':'Pangolin integration request failed.'}
 const finished=new Date().toISOString();
 // The configuration revision and lease fence late writes after edits or deletion.
 const valid="id=? AND owner=? AND revision=? AND lease=? AND EXISTS (SELECT 1 FROM integrations WHERE integrations.id=classic_cache.id AND integrations.revision=classic_cache.revision AND integrations.connector='pangolin')";
 let written; if(!error&&snapshot)written=await db.prepare('UPDATE classic_cache SET session=?,snapshot=?,last_success=?,error=NULL,next_due=?,lease=NULL,lease_until=0 WHERE '+valid).bind(null,JSON.stringify(snapshot),finished,now+60000,id,owner,revision,lease).run();else written=await db.prepare('UPDATE classic_cache SET session=?,error=?,next_due=?,lease=NULL,lease_until=0 WHERE '+valid).bind(null,error,now+60000,id,owner,revision,lease).run();
 if(!written.meta.changes)return {...classicView(null),skipped:true,status:'Configuration changed; poll discarded'};
 await db.prepare("UPDATE integrations SET status=?,latency=?,checked_at=? WHERE id=? AND owner=? AND revision=?").bind(error?'Pangolin polling failed':'Connected',Date.now()-start,finished,id,owner,revision).run();let row=await db.prepare('SELECT * FROM classic_cache WHERE id=? AND owner=?').bind(id,owner).first();return {...classicView(row),skipped:false,status:error?'Pangolin polling failed':'Connected',latency:Date.now()-start}
}
