export class ApiError extends Error{constructor(message,status=400){super(message);this.status=status}}
export function endpoint(value,privateTarget=false){let u;try{u=new URL(value)}catch{throw new ApiError('Enter a valid endpoint URL.')}if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.hash||u.search)throw new ApiError('Use HTTP(S) without embedded credentials, fragments or queries.');const host=u.hostname.toLowerCase();if(['localhost','169.254.169.254','metadata.google.internal'].includes(host)||host.startsWith('127.')||host==='[::1]'||host.startsWith('169.254.'))throw new ApiError('Loopback and metadata endpoints are not allowed.');return u.href;}
export function publicIP(ip){if(ip.includes(':')){let s=ip.toLowerCase();return !s.startsWith('::')&&!/^(fc|fd|fe[89ab]|ff|2001:db8)/.test(s)&&/^[23]/.test(s)}let a=ip.split('.').map(Number);return a.length===4&&a.every(n=>Number.isInteger(n)&&n>=0&&n<=255)&&a[0]!==0&&a[0]!==10&&a[0]!==127&&a[0]<224&&!(a[0]===169&&a[1]===254)&&!(a[0]===172&&a[1]>=16&&a[1]<=31)&&!(a[0]===192&&a[1]===168)&&!(a[0]===100&&a[1]>=64&&a[1]<=127)&&!(a[0]===198&&[18,19,51].includes(a[1]))&&!(a[0]===192&&a[1]===0)&&!(a[0]===203&&a[1]===0)}
export async function ensurePublic(url){endpoint(url);}
export function headerName(v){if(!/^[A-Za-z][A-Za-z0-9-]{0,63}$/.test(v)||/^(host|cookie|connection|content-length|content-type|origin|referer|proxy-.*|sec-.*|oai-.*|cf-.*|x-forwarded-.*)$/i.test(v))throw new ApiError('Choose a valid authentication header, such as Authorization or X-API-Key.');return v}
export function cleanSecret(v){if(typeof v!=='string'||v.length>8192||/[\r\n\0]/.test(v))throw new ApiError('Credential is invalid or too long.');return v}
function base64(bytes){return btoa(String.fromCharCode(...bytes))}function unbase64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function encryptionKey(hex){if(!/^[a-f0-9]{64}$/.test(hex||''))throw new ApiError('Credential storage is not configured.',503);return crypto.subtle.importKey('raw',Uint8Array.from(hex.match(/../g),s=>parseInt(s,16)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function encrypt(value,key,context){let iv=crypto.getRandomValues(new Uint8Array(12));let ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(context)},await encryptionKey(key),new TextEncoder().encode(JSON.stringify(value)));return JSON.stringify({v:1,iv:base64(iv),data:base64(new Uint8Array(ciphertext))})}
export async function decrypt(value,key,context){let c=JSON.parse(value);let bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:unbase64(c.iv),additionalData:new TextEncoder().encode(context)},await encryptionKey(key),unbase64(c.data));return JSON.parse(new TextDecoder().decode(bytes))}
export function authHeaders(auth,header,secret){const headers={Accept:'application/json'};if(auth==='bearer')headers.Authorization='Bearer '+cleanSecret(secret.key);if(auth==='header')headers[headerName(header)]=cleanSecret(secret.key);if(auth==='basic')headers.Authorization='Basic '+btoa(String.fromCharCode(...new TextEncoder().encode(cleanSecret(secret.username)+':'+cleanSecret(secret.password))));return headers}
export function safeIntegration(r){return {orgId:r.org_id||'',id:r.id,connector:r.connector||'generic',name:r.name,endpoint:r.endpoint,target:r.target,mode:r.mode,auth:r.auth,proxyAuth:!!r.proxy_auth,header:r.header,customer:r.customer,status:r.status,httpCode:r.http_code,latency:r.latency,checkedAt:r.checked_at,createdAt:r.created_at,hasCredential:r.auth!=='none',hasBridgeToken:r.mode==='bridge'}}
export async function smallJson(response,max=8192){if(!response.body)throw new ApiError('Empty bridge response.',502);const reader=response.body.getReader();let size=0,chunks=[];try{while(true){const {value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>max)throw new ApiError('Bridge response too large.',502);chunks.push(value)}let data=new Uint8Array(size),offset=0;for(let c of chunks){data.set(c,offset);offset+=c.byteLength}return JSON.parse(new TextDecoder().decode(data))}finally{await reader.cancel()}}

/** @returns {Record<string,string>} */
export function proxyHeaders(secret,enabled=false){return enabled?{"P-Access-Token-Id":cleanSecret(secret.proxyId),"P-Access-Token":cleanSecret(secret.proxyToken)}:{}}
