import {ApiError,ensurePublic,endpoint,encrypt,decrypt,proxyHeaders,smallJson} from './security.js';
export class ClassicError extends Error{}
const maxText=(v,n=200)=>typeof v==='string'?v.slice(0,n):null;
const number=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0?v:null;
export function sanitizeDevices(records){return records.map(d=>{const state=typeof d.state==='number'&&Number.isInteger(d.state)?d.state:null;const adopted=typeof d.adopted==='boolean'?d.adopted:null;let out={name:maxText(d.name),model:maxText(d.model),adopted,state,recordType:adopted===true?'adopted':adopted===false?'discovery/pending':'unknown',connectionState:state===1?'connected':state===0?'disconnected':state===null?'unknown':'pending/other'};for(const k of ['uptime','num_sta'])if(number(d[k])!==null)out[k]=d[k];if(typeof d.version==='string')out.version=maxText(d.version);return out})}
export class CookieJar{
 constructor(cookies=[]){this.cookies=cookies}
 absorb(headers,url,now=Date.now()){
  const u=new URL(url);let lines=[];if(typeof headers.getSetCookie==='function')lines=headers.getSetCookie();else if(typeof headers.getAll==='function')lines=headers.getAll('Set-Cookie');else lines=(headers.get('set-cookie')||'').split(/,(?=\s*[^;,=\s]+=[^;]*)/);
  for(let line of lines){let parts=line.split(';'),first=parts.shift(),index=first.indexOf('=');if(index<1)continue;let name=first.slice(0,index).trim(),value=first.slice(index+1).trim();if(!/^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/.test(name)||/[\r\n\0;]/.test(value))continue;let cookie={name,value,domain:u.hostname,hostOnly:true,path:u.pathname.slice(0,u.pathname.lastIndexOf('/')+1)||'/',secure:false,expires:null};let valid=true,hasAge=false;for(let raw of parts){let [key,...rest]=raw.trim().split('='),val=rest.join('=');key=key.toLowerCase();if(key==='domain'){let domain=val.toLowerCase().replace(/^\./,'');if(u.hostname!==domain&&!u.hostname.endsWith('.'+domain)){valid=false;break}cookie.domain=domain;cookie.hostOnly=false}if(key==='path'&&val.startsWith('/'))cookie.path=val;if(key==='secure')cookie.secure=true;if(key==='max-age'&&/^-?\d+$/.test(val)){cookie.expires=now+Number(val)*1000;hasAge=true}if(key==='expires'&&!hasAge){let time=Date.parse(val);if(Number.isFinite(time))cookie.expires=time}}if(!valid)continue;
   this.cookies=this.cookies.filter(c=>!(c.name===name&&c.domain===cookie.domain&&c.path===cookie.path));if(cookie.expires===null||cookie.expires>now)this.cookies.push(cookie)
  }
  this.cookies=this.cookies.filter(c=>c.expires===null||c.expires>now).slice(-100)
 }
 header(url,now=Date.now()){let u=new URL(url);return this.cookies.filter(c=>(c.expires===null||c.expires>now)&&(c.hostOnly?u.hostname===c.domain:u.hostname===c.domain||u.hostname.endsWith('.'+c.domain))&&(!c.secure||u.protocol==='https:')&&(u.pathname===c.path||u.pathname.startsWith(c.path.endsWith('/')?c.path:c.path+'/'))).sort((a,b)=>b.path.length-a.path.length).map(c=>c.name+'='+c.value).join('; ')}
}
export class ClassicSession{
 constructor(base,secret,jar=[],options={}){const u=new URL(endpoint(base));if(u.pathname!=='/')throw new ClassicError('Classic connector requires the base URL without an API path.');this.base=u.origin;this.secret=secret;this.jar=new CookieJar(jar);this.fetch=options.fetcher||fetch;this.signal=options.signal;this.proxy=options.proxy||false;this.reauthenticated=false;this.identityKey=options.identityKey;this.identityContext=options.identityContext}
 async request(path,method='GET',body){if(!(method==='POST'&&path==='/api/login')&&!(method==='GET'&&(path==='/api/self/sites'||/^\/api\/s\/[^/?#]+\/stat\/(device|sta|health)$/.test(path))))throw new ClassicError('Read endpoint not allowed.');const url=this.base+path;const cookie=this.jar.header(url);const headers={Accept:'application/json',...proxyHeaders(this.secret,this.proxy),...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':'application/json'}:{})};let r;try{r=await this.fetch(url,{method,headers,...(body?{body:JSON.stringify(body)}:{}),redirect:'manual',signal:this.signal?AbortSignal.any([this.signal,AbortSignal.timeout(10000)]):AbortSignal.timeout(10000)})}catch{throw new ClassicError('Connection or TLS request failed.')}this.jar.absorb(r.headers,url);return r}
 async parse(r,login=false){if(r.status>=300&&r.status<400){await r.body?.cancel();throw new ClassicError('Redirect returned by controller or proxy.')}if(r.status!==200){await r.body?.cancel();throw new ClassicError('Controller or proxy returned HTTP '+r.status+'.')}let data;try{data=await smallJson(r,4*1024*1024)}catch{throw new ClassicError('Invalid or oversized JSON response.')}if(data?.meta?.rc!=='ok')throw new ClassicError('UniFi API reported an integration error.');if(!login&&!Array.isArray(data.data))throw new ClassicError('UniFi API returned an invalid data array.');return data}
 async login(){this.jar=new CookieJar();let r=await this.request('/api/login','POST',{username:this.secret.username,password:this.secret.password});await this.parse(r,true);if(!this.jar.header(this.base+'/api/self/sites'))throw new ClassicError('Login did not provide a usable session cookie.')}
 async read(path){let r=await this.request(path);if((r.status===401||r.status===403)&&!this.reauthenticated){await r.body?.cancel();this.reauthenticated=true;await this.login();r=await this.request(path)}return (await this.parse(r)).data}
 async identifyDevices(records,site){const sanitized=sanitizeDevices(records);if(!this.identityKey)return sanitized;const keyBytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('jdln-asset-identity-v1:'+this.identityKey));const key=await crypto.subtle.importKey('raw',keyBytes,{name:'HMAC',hash:'SHA-256'},false,['sign']);return Promise.all(sanitized.map(async(d,n)=>{const raw=records[n],identity=typeof raw.mac==='string'?raw.mac.toLowerCase():typeof raw._id==='string'?raw._id:JSON.stringify([d.name,d.model]);const message=JSON.stringify([this.identityContext,site,identity]);const digest=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(message));return {...d,assetId:Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('')}}))}
 async collect(forceLogin=false){if(forceLogin||!this.jar.header(this.base+'/api/self/sites'))await this.login();const sites=await this.read('/api/self/sites');if(!sites.length)throw new ClassicError('No accessible sites returned.');if(sites.length>100)throw new ClassicError('More than 100 sites returned; split this deployment before polling.');let output=[];
  for(const site of sites){if(typeof site.name!=='string'||!site.name||site.name.length>256)throw new ClassicError('Site identifier is missing or invalid.');let root='/api/s/'+encodeURIComponent(site.name)+'/stat/';let devices=await this.read(root+'device');let clients=await this.read(root+'sta');let health=await this.read(root+'health');output.push({name:site.name,desc:maxText(site.desc,256),devices:await this.identifyDevices(devices,site.name),connectedClientCount:clients.length,health:health.map(h=>({subsystem:maxText(h.subsystem),status:maxText(h.status)}))})}
  return {sites:output}
 }
}
export function classicView(row,now=Date.now()){let data=row?.snapshot?JSON.parse(row.snapshot):null;const success=row?.last_success||null;return {data,lastSuccess:success,lastAttempt:row?.last_attempt||null,stale:!success||!!row?.error||now-Date.parse(success)>120000,error:row?.error||null,pollIntervalSeconds:60,nextDue:row?.next_due||0,polling:!!row?.lease&&row.lease_until>now}}
export async function pollClassic(env,record,{force=false,test=false,fetcher=fetch,now=Date.now()}={}){
 const db=env.DB,owner=record.owner,id=record.id,revision=record.revision;await db.prepare("INSERT INTO classic_cache (id,owner,revision) SELECT id,owner,revision FROM integrations WHERE id=? AND owner=? AND revision=? AND connector='unifi-classic' ON CONFLICT(id) DO NOTHING").bind(id,owner,revision).run();const lease=crypto.randomUUID();const claimed=await db.prepare('UPDATE classic_cache SET lease=?,lease_until=?,last_attempt=? WHERE id=? AND owner=? AND revision=? AND lease_until<=? AND (next_due<=? OR ?=1)').bind(lease,now+90000,new Date(now).toISOString(),id,owner,revision,now,now,force?1:0).run();if(!claimed.meta.changes){let row=await db.prepare('SELECT * FROM classic_cache WHERE id=? AND owner=?').bind(id,owner).first();return {...classicView(row),skipped:true,status:row?.lease_until>now?'Poll already in progress':'Cached · next poll not due'}}
 let session,snapshot,error=null,encryptedSession=null;const start=Date.now();try{await ensurePublic(record.endpoint,fetcher);let secret=await decrypt(record.encrypted,env.INTEGRATION_ENCRYPTION_KEY,owner+':'+id);const row=await db.prepare('SELECT session FROM classic_cache WHERE id=? AND owner=?').bind(id,owner).first();let jar=row?.session?await decrypt(row.session,env.INTEGRATION_ENCRYPTION_KEY,owner+':'+id+':session'):[];session=new ClassicSession(record.endpoint,secret,jar,{fetcher,signal:AbortSignal.timeout(50000),proxy:!!record.proxy_auth,identityKey:env.INTEGRATION_ENCRYPTION_KEY,identityContext:owner+':'+id});snapshot=await session.collect(test);if(JSON.stringify(snapshot).length>750000)throw new ClassicError('Whitelisted snapshot exceeds the storage limit.')}catch(e){error=e instanceof ClassicError?e.message:e instanceof ApiError?'Endpoint DNS validation failed.':'Classic integration request failed.'}
 if(session){try{encryptedSession=await encrypt(session.jar.cookies,env.INTEGRATION_ENCRYPTION_KEY,owner+':'+id+':session')}catch{error='Session storage failed.'}}
 const finished=new Date().toISOString();
 // The configuration revision and lease fence late writes after edits or deletion.
 const valid="id=? AND owner=? AND revision=? AND lease=? AND EXISTS (SELECT 1 FROM integrations WHERE integrations.id=classic_cache.id AND integrations.revision=classic_cache.revision AND integrations.connector='unifi-classic')";
 let written; if(!error&&snapshot)written=await db.prepare('UPDATE classic_cache SET session=?,snapshot=?,last_success=?,error=NULL,next_due=?,lease=NULL,lease_until=0 WHERE '+valid).bind(encryptedSession,JSON.stringify(snapshot),finished,now+60000,id,owner,revision,lease).run();else written=await db.prepare('UPDATE classic_cache SET session=?,error=?,next_due=?,lease=NULL,lease_until=0 WHERE '+valid).bind(encryptedSession,error,now+60000,id,owner,revision,lease).run();
 if(!written.meta.changes)return {...classicView(null),skipped:true,status:'Configuration changed; poll discarded'};
 await db.prepare("UPDATE integrations SET status=?,latency=?,checked_at=? WHERE id=? AND owner=? AND revision=?").bind(error?'Classic polling failed':'Connected',Date.now()-start,finished,id,owner,revision).run();let row=await db.prepare('SELECT * FROM classic_cache WHERE id=? AND owner=?').bind(id,owner).first();return {...classicView(row),skipped:false,status:error?'Classic polling failed':'Connected',latency:Date.now()-start}
}
